<%
'French localisation strings
Application("fr.loc")="true"

Application("fr.logon.title")="Bienvenue"
Application("fr.logon.logon.title.1")="Pas un utilisateur encore?"
Application("fr.logon.logon.title.2")="Créez un compte"
Application("fr.user")="Utilisateur"
Application("fr.password")="Mot de passe"
Application("fr.enter")="entrez"
Application("fr.logon.applets")="Ce website emploie Java<sup>tm</sup > applets"

Application("fr.username")="Nom d'utilisateur"
Application("fr.email")="E-mail"
Application("fr.display")="Nom"
Application("fr.homepg")="Web page (url)"
Application("fr.photo")="Photo (url)"
Application("fr.distances")="Distances dedans"
Application("fr.km")="kilomètres"
Application("fr.mi")="milles"
Application("fr.and")="et"
Application("fr.back")="Page précédente"
Application("fr.next")="Suivante"
Application("fr.hometown")="Ville de résidence"

Application("fr.links.trips")="Voyages"
Application("fr.links.buddies")="Contacts"
Application("fr.links.distance")="Distance"
Application("fr.links.profile")="Profil"
Application("fr.links.disconnect")="Débrancher"

Application("fr.menu.title")="Menu"
Application("fr.mytrips.current.title")="Mes voyages"
Application("fr.mytrips.archived.title")="Voyages archivés"
Application("fr.mytrips.delete.comfirm")="Êtes vous sûr vous voulez supprimer ce voyage?"
Application("fr.newtrip.title")="Nouveau voyage"
Application("fr.trips.empty")="Il n'y a aucun voyage à montrer"

Application("fr.search.title")="Insérez le nom de l'endroit"
Application("fr.search.equals")="Égale à"
Application("fr.search.startswith")="Débuts avec"
Application("fr.search.contains")="Contient"
Application("fr.search")="Rechercher"
Application("fr.search.filtered")="Quelques résultats ne sont pas montrés, filtre svp par pays"

Application("fr.location")="Endroit"
Application("fr.start")="Début"
Application("fr.end")="Fin"
Application("fr.delete")="Supprimer"
Application("fr.archive")="Archiver"
Application("fr.dearchive")="Dearchiver"
Application("fr.buddy")="Contact"
Application("fr.currentLoc")="Endroit courant"
Application("fr.distance")="Distance"
Application("fr.trip")="Voyage"
Application("fr.mytrip")="Mon voyage"
Application("fr.day")="Jour"
Application("fr.month")="Mois"
Application("fr.year")="Anné"
Application("fr.accept")="Accepter"
Application("fr.reject")="Rejet"
Application("fr.cancel")="Cancel"
Application("fr.country")="Pays"
Application("fr.region")="Région"
Application("fr.select")="Choisire"
Application("fr.seconds")="secondes"
Application("fr.save")="Stocker"
Application("fr.date")="Date"
Application("fr.log")="Notations"
Application("fr.modify")="Modifier"
Application("fr.comments")="Commentaires"
Application("fr.category")="Catégories"
Application("fr.yes")="Oui"


Application("fr.buddies.title")="Mes contacts"
Application("fr.newBuddy.title")="Nouveau contact"
Application("fr.newBuddy.help")="Insérez le nom d'utilisateur de la personne que vous voulez vous ajouter"
Application("fr.newBuddy.form")="Ajouter un contact"
Application("fr.newbuddy.done")="doit accepter votre invitation avant que vous deveniez des copains"
Application("fr.buddytrack.title")="Dépistez vos copains"
Application("fr.matches.title")="Coïncidences"
Application("fr.invitations.title")="Invitations"
Application("fr.mylog.title")="Notations"
Application("fr.newuser.title")="Nouveau utilisateur"
Application("fr.plot.title")="Carte"
Application("fr.newtrip.title")="Nouveau voyage"

Application("fr.menu.welcome")="Bienvenue"
Application("fr.menu.1")="Vous êtes actuellement dedans "
Application("fr.menu.2")="Note: cette information peut être imprécise si vous avez des voyages avec une même date ou en raison des fuseaux horaires"

Application("fr.invitations.nopending")="Vous n'avez aucune invitation en suspens"
Application("fr.invitations.pending")="Vous avez les invitations suivantes de devenir des copains"

Application("fr.newtrip.1")="Je visitarai "
Application("fr.newtrip.2")=" dans les dates suivantes"
Application("fr.newtrip.sharewith")="Voyage de part avec"
Application("fr.newtrip.description")="Déscription du voyage"

Application("fr.search.empty")="Votre recherche n'a renvoyé aucun résultat"
Application("fr.search.took")="Votre recherche a pris"

Application("fr.log.new")="Nouvelle notation"
Application("fr.log.update")="Modifiez la notation"
Application("fr.log.sharewith")="Notation de part avec"
Application("fr.log.empty")="Il n'y a aucune notation à montrer"

Application("fr.share.all")="Tous mes copains"
Application("fr.share.friends")="Amis"
Application("fr.share.family")="Famille"
Application("fr.share.work")="Travaille"
Application("fr.share.other")="Autres"

Application("fr.buddy.visithomepage")="Voire website"
Application("fr.buddy.delete.confirm.1")="ne serais pas copains"
Application("fr.buddy.delete.confirm.2")="Confirmez cette opération?"

Application("fr.buddytrips.title")="Les voyages de mon copain"
Application("fr.account.logon")="Entrez"

Application("fr.dist.first")="Recherchez le premier endroit"
Application("fr.dist.second")="Recherchez le deuxième endroit"
Application("fr.dist.result.1")="La distance entre"
Application("fr.dist.result.2")="est approximativement"

Application("fr.profile.change")="Clickez pour changer"
Application("fr.profile.change.pwd")="votre mot de passe"
Application("fr.profile.change.hometown")="en tant que votre ville de résidence"
Application("fr.profile.change.pwd.title")="Changer la mot de passe"
Application("fr.profile.change.pwd.old")="Vieux mot de passe"
Application("fr.profile.change.pwd.new")="Nouveau mot de passe"
Application("fr.profile.change.pwd.confirm")="Confirmez votre mot de passe"
Application("fr.profile.change.hometown.title")="Changer votre ville de résidence"
Application("fr.profile.change.ok")="Information stockée"
Application("fr.profile.change.nok.old")="Votre vieux mot de passe ne s'assortit pas"
Application("fr.profile.change.nok.match")="Vos nouveaux mots de passe ne s'assortissent pas"

Application("fr.form.baddata")="L'information est inadmissible ou inachevée"

Application("fr.buddytrack.1")="Déterminez où vos copains seront une date donnée"
Application("fr.buddytrack.2")="Vos copains seront dans les endroits suivants"
Application("fr.buddies.none")="Vous n'avez aucun copain"

Application("fr.matches.1")="Voyages qui assortissent vos copains"
Application("fr.matches.filter")="Distance maximum"
Application("fr.matches.filtered")="Quelques coïncidences ont été filtrées pendant qu'elles étaient au delà de la distance maximum"
Application("fr.matches.none")="Aucunes coïncidences"

Application("fr.newuser.help")="Veuillez remplir l'information demandée"
Application("fr.newuser.error.dupe")="L'utilisateur déjà existe, satisfait choisissent encore"
Application("fr.newuser.ok")="Des félicitations, votre compte ont été crée avec l'information suivante"

Application("fr.month.1")="Jan"
Application("fr.month.2")="Fév"
Application("fr.month.3")="Mar"
Application("fr.month.4")="Avr"
Application("fr.month.5")="May"
Application("fr.month.6")="Juin"
Application("fr.month.7")="Juil"
Application("fr.month.8")="Aoû"
Application("fr.month.9")="Sep"
Application("fr.month.10")="Oct"
Application("fr.month.11")="Nov"
Application("fr.month.12")="Déc"

Application("fr.plotter.capLabels")="Étiquettes"
Application("fr.plotter.capConnect")="Relier"
Application("fr.plotter.capBoundaries")="Frontières "
Application("fr.plotter.capCountries")="Pays"
Application("fr.plotter.capFlags")="Drapeaux"
%>