<%
'Spanish localisation strings

Application("es.loc")="true"

Application("es.logon.title")="Bienvenido"
Application("es.logon.logon.title.1")="¿No eres un usuario todavía?"
Application("es.logon.logon.title.2")="crea una cuenta"
Application("es.user")="Usuario"
Application("es.password")="Contraseña"
Application("es.enter")="entrar"
Application("es.logon.applets")="Este sitio web emplea applets de Java<sup>tm</sup>"

Application("es.username")="Nombre de usuario"
Application("es.email")="Correo electrónico"
Application("es.display")="Nombre completo"
Application("es.homepg")="Página web (url)"
Application("es.photo")="Foto (url)"
Application("es.distances")="Distancias en"
Application("es.km")="kilómetros"
Application("es.mi")="millas"
Application("es.and")="y"
Application("es.back")="Página anterior"
Application("es.next")="Siguiente"
Application("es.hometown")="Ciudad de residencia"

Application("es.links.trips")="Viajes"
Application("es.links.buddies")="Contactos"
Application("es.links.distance")="Distancia"
Application("es.links.profile")="Perfil"
Application("es.links.disconnect")="Desconectar"

Application("es.menu.title")="Menú"
Application("es.mytrips.current.title")="Mis viajes"
Application("es.mytrips.archived.title")="Viajes archivados"
Application("es.mytrips.delete.comfirm")="¿Estás seguro de que quieres borrar este viaje?"
Application("es.newtrip.title")="Viaje nuevo"
Application("es.trips.empty")="No hay ningún viaje para mostrar"

Application("es.search.title")="Introduce el nombre del lugar"
Application("es.search.equals")="Igual a"
Application("es.search.startswith")="Empieza por"
Application("es.search.contains")="Contiene"
Application("es.search")="Buscar"
Application("es.search.filtered")="No se muestran todos los resultados.  Por favor, realiza una búsqueda especificando el país"

Application("es.location")="Lugar"
Application("es.start")="Inicio"
Application("es.end")="Fin"
Application("es.delete")="Borrar"
Application("es.archive")="Archivar"
Application("es.dearchive")="Desarchivar"
Application("es.buddy")="Contacto"
Application("es.currentLoc")="Ubicación actual"
Application("es.distance")="Distancia"
Application("es.trip")="Viaje"
Application("es.mytrip")="Mi viaje"
Application("es.day")="Día"
Application("es.month")="Mes"
Application("es.year")="Año"
Application("es.accept")="Aceptar"
Application("es.reject")="Rechazar"
Application("es.cancel")="Cancelar"
Application("es.country")="País"
Application("es.region")="Región"
Application("es.select")="Seleccionar"
Application("es.seconds")="segundos"
Application("es.save")="Guardar"
Application("es.date")="Fecha"
Application("es.log")="Apunte"
Application("es.modify")="Modificar"
Application("es.comments")="Comentarios"
Application("es.category")="Categoría"
Application("es.yes")="Sí"


Application("es.buddies.title")="Mis Contactos"
Application("es.newBuddy.title")="Nuevo contacto"
Application("es.newBuddy.help")="Introduce el nombre de usuario de la persona que desees agregar"
Application("es.newBuddy.form")="Agregar un contacto"
Application("es.newbuddy.done")="te ha de aceptar la invitación para que seáis contactos"
Application("es.buddytrack.title")="Seguimiento de mis contactos"
Application("es.matches.title")="Coincidencias"
Application("es.invitations.title")="Invitaciones"
Application("es.mylog.title")="Apuntes"
Application("es.newuser.title")="Usuario nuevo"
Application("es.plot.title")="Mapa"
Application("es.newtrip.title")="Viaje nuevo"

Application("es.menu.welcome")="¡Bienvenido"
Application("es.menu.1")="Actualmente estás en "
Application("es.menu.2")="Nota: Esta información puede ser incorrecta si tienes viajes solapados o por motivos de diferencias horarias"

Application("es.invitations.nopending")="No tienes ninguna invitación pendiente"
Application("es.invitations.pending")="Las siguientes personas desean agregarte como contacto"

Application("es.newtrip.1")="Visitaré "
Application("es.newtrip.2")=" en las siguientes fechas"
Application("es.newtrip.sharewith")="Compartir viaje con"
Application("es.newtrip.description")="Descripción del viaje"

Application("es.search.empty")="Tu búsqueda no devolvió ningún resultado"
Application("es.search.took")="Tu búsqueda tardó"

Application("es.log.new")="Nuevo apunte"
Application("es.log.update")="Modificar apunte"
Application("es.log.sharewith")="Compartir apunte con"
Application("es.log.empty")="No hay ningún apunte para mostrar"

Application("es.share.all")="Todos mis contactos"
Application("es.share.friends")="Amigos"
Application("es.share.family")="Familia"
Application("es.share.work")="Trabajo"
Application("es.share.other")="Otros"

Application("es.buddy.visithomepage")="Ver página web"
Application("es.buddy.delete.confirm.1")="dejará de ser tu contacto y tú el suyo"
Application("es.buddy.delete.confirm.2")="¿Deseas confirmar esta operación?"

Application("es.buddytrips.title")="Viajes de mi contacto"
Application("es.account.logon")="Inicia tu sesión"

Application("es.dist.first")="Busca el primer lugar"
Application("es.dist.second")="Busca el segundo lugar"
Application("es.dist.result.1")="La distancia entre"
Application("es.dist.result.2")="es de aproximadamente"

Application("es.profile.change")="Pincha para cambiar"
Application("es.profile.change.pwd")="tu contraseña"
Application("es.profile.change.hometown")="como tu ciudad de residencia"
Application("es.profile.change.pwd.title")="Cambio de contraseña"
Application("es.profile.change.pwd.old")="Contraseña antigua"
Application("es.profile.change.pwd.new")="Contraseña nueva"
Application("es.profile.change.pwd.confirm")="Confirmar contraseña nueva"
Application("es.profile.change.hometown.title")="Introduce tu ciudad de residencia"
Application("es.profile.change.ok")="Cambios guardados correctamente"
Application("es.profile.change.nok.old")="Tu contraseña antigua no es correcta"
Application("es.profile.change.nok.match")="Tu contraseña nueva no coincide"

Application("es.form.baddata")="Información no válida o incompleta"

Application("es.buddytrack.1")="Introduce una fecha y sabrás dónde estarán tus contactos ese día"
Application("es.buddytrack.2")="Tus contactos estarán en estos lugares"
Application("es.buddies.none")="No tienes ningún contacto"

Application("es.matches.1")="Viajes coincidentes con tus contactos"
Application("es.matches.filter")="Distancia máxima"
Application("es.matches.filtered")="Se filtraron coincidencias que superaban la distancia máxima"
Application("es.matches.none")="No hay coincidencias"

Application("es.newuser.help")="Por favor, introduce la informacion requerida"
Application("es.newuser.error.dupe")="El nombre de usuario ya existe, selecciona otro distinto"
Application("es.newuser.ok")="Enhorabuena, tu cuenta se ha creado con la siguiente información"

Application("es.month.1")="Ene"
Application("es.month.2")="Feb"
Application("es.month.3")="Mar"
Application("es.month.4")="Abr"
Application("es.month.5")="May"
Application("es.month.6")="Jun"
Application("es.month.7")="Jul"
Application("es.month.8")="Ago"
Application("es.month.9")="Sep"
Application("es.month.10")="Oct"
Application("es.month.11")="Nov"
Application("es.month.12")="Dic"

Application("es.plotter.capLabels")="Etiquetas"
Application("es.plotter.capConnect")="Conectar"
Application("es.plotter.capBoundaries")="Fronteras"
Application("es.plotter.capCountries")="Países"
Application("es.plotter.capFlags")="Banderas"
%>