<%
'Spanish localisation strings

Application("en.loc")="true"

Application("en.logon.title")="Welcome"
Application("en.logon.logon.title.1")="Not a user yet?"
Application("en.logon.logon.title.2")="Create an account"
Application("en.user")="User"
Application("en.password")="Password"
Application("en.enter")="enter"
Application("en.logon.applets")="This website uses Java<sup>tm</sup> applets"

Application("en.username")="User name"
Application("en.email")="E-mail"
Application("en.display")="Display name"
Application("en.homepg")="Web page (url)"
Application("en.photo")="Photo (url)"
Application("en.distances")="Distances in"
Application("en.km")="kilometers"
Application("en.mi")="miles"
Application("en.and")="and"
Application("en.back")="Previous page"
Application("en.next")="Next"
Application("en.hometown")="City of residence"

Application("en.links.trips")="Trips"
Application("en.links.buddies")="Buddies"
Application("en.links.distance")="Distance"
Application("en.links.profile")="Profile"
Application("en.links.disconnect")="Disconnect"

Application("en.menu.title")="Menu"
Application("en.mytrips.current.title")="My trips"
Application("en.mytrips.archived.title")="Archived trips"
Application("en.mytrips.delete.comfirm")="Are you sure you want to delete this trip?"
Application("en.newtrip.title")="New trip"
Application("en.trips.empty")="There are no trips to display"

Application("en.search.title")="Insert the name of the location"
Application("en.search.equals")="Equals"
Application("en.search.startswith")="Starts with"
Application("en.search.contains")="Contains"
Application("en.search")="Search"
Application("en.search.filtered")="Some results are not displayed, please filter by country"

Application("en.location")="Location"
Application("en.start")="Start"
Application("en.end")="End"
Application("en.delete")="Delete"
Application("en.archive")="Archive"
Application("en.dearchive")="Dearchive"
Application("en.buddy")="Buddy"
Application("en.currentLoc")="Current location"
Application("en.distance")="Distance"
Application("en.trip")="Trip"
Application("en.mytrip")="My trip"
Application("en.day")="Day"
Application("en.month")="Month"
Application("en.year")="Year"
Application("en.accept")="Accept"
Application("en.reject")="Reject"
Application("en.cancel")="Cancel"
Application("en.country")="Country"
Application("en.region")="Region"
Application("en.select")="Select"
Application("en.seconds")="seconds"
Application("en.save")="Save"
Application("en.date")="Date"
Application("en.log")="Log"
Application("en.modify")="Modify"
Application("en.comments")="Comments"
Application("en.category")="Category"
Application("en.yes")="Yes"


Application("en.buddies.title")="My buddies"
Application("en.newBuddy.title")="New buddy"
Application("en.newBuddy.help")="Insert the user name of the person you want to add"
Application("en.newBuddy.form")="Add a buddy"
Application("en.newbuddy.done")="must accept your invitation before you become buddies"
Application("en.buddytrack.title")="Track your buddies"
Application("en.matches.title")="Matches"
Application("en.invitations.title")="Invitations"
Application("en.mylog.title")="Log"
Application("en.newuser.title")="New user"
Application("en.plot.title")="Plot"
Application("en.newtrip.title")="New trip"

Application("en.menu.welcome")="Welcome"
Application("en.menu.1")="You currently are in "
Application("en.menu.2")="Note: this information can be inaccurate if you have overlapping trips or due to time-zone offsets"

Application("en.invitations.nopending")="You have no pending invitations"
Application("en.invitations.pending")="You have the following invitations to become buddies"

Application("en.newtrip.1")="I will visit "
Application("en.newtrip.2")=" in the following dates"
Application("en.newtrip.sharewith")="Share trip with"
Application("en.newtrip.description")="Trip's description"

Application("en.search.empty")="Your search returned no results"
Application("en.search.took")="Your search took"

Application("en.log.new")="New log"
Application("en.log.update")="Modify log"
Application("en.log.sharewith")="Share log with"
Application("en.log.empty")="There are no logs to display"

Application("en.share.all")="All of my buddies"
Application("en.share.friends")="Friends"
Application("en.share.family")="Family"
Application("en.share.work")="Work"
Application("en.share.other")="Other"

Application("en.buddy.visithomepage")="View website"
Application("en.buddy.delete.confirm.1")="will no longer be buddies"
Application("en.buddy.delete.confirm.2")="Confirm this operation?"

Application("en.buddytrips.title")="My buddy's trips"
Application("en.account.logon")="Log on"

Application("en.dist.first")="Search the first location"
Application("en.dist.second")="Search the second location"
Application("en.dist.result.1")="The distance between"
Application("en.dist.result.2")="is approximately"

Application("en.profile.change")="Click to change"
Application("en.profile.change.pwd")="your password"
Application("en.profile.change.hometown")="as your city of residence"
Application("en.profile.change.pwd.title")="Password change"
Application("en.profile.change.pwd.old")="Old password"
Application("en.profile.change.pwd.new")="New password"
Application("en.profile.change.pwd.confirm")="Confirm your password"
Application("en.profile.change.hometown.title")="Change your city of residence"
Application("en.profile.change.ok")="Information saved"
Application("en.profile.change.nok.old")="Your old password doesn't match"
Application("en.profile.change.nok.match")="Your new passwords don't match"

Application("en.form.baddata")="Invalid or incomplete information"

Application("en.buddytrack.1")="Determine where your buddies will be on a given date"
Application("en.buddytrack.2")="Your buddies will be in the following locations"
Application("en.buddies.none")="You have no buddies"

Application("en.matches.1")="Trips that match your buddie's"
Application("en.matches.filter")="Maximum distance"
Application("en.matches.filtered")="Some matches were filtered as they were beyond the maximum distance"
Application("en.matches.none")="No matches"

Application("en.newuser.help")="Please complete the information requested"
Application("en.newuser.error.dupe")="The user already exists, please choose another one"
Application("en.newuser.ok")="Congratulations, your account has been created with the following information"

Application("en.month.1")="Jan"
Application("en.month.2")="Feb"
Application("en.month.3")="Mar"
Application("en.month.4")="Apr"
Application("en.month.5")="May"
Application("en.month.6")="Jun"
Application("en.month.7")="Jul"
Application("en.month.8")="Aug"
Application("en.month.9")="Sep"
Application("en.month.10")="Oct"
Application("en.month.11")="Nov"
Application("en.month.12")="Dic"

Application("en.plotter.capLabels")="Labels"
Application("en.plotter.capConnect")="Connect"
Application("en.plotter.capBoundaries")="Boundaries"
Application("en.plotter.capCountries")="Countries"
Application("en.plotter.capFlags")="Flags"

%>